DROP TABLE IF EXISTS CARD CASCADE;
CREATE TABLE CARD
(
    CARD_ID BIGSERIAL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (CARD_ID)
);
CREATE INDEX CARD_USER_ID_INDEX ON CARD(USER_ID);
DROP TABLE IF EXISTS BALANCE CASCADE;
CREATE TABLE BALANCE
(
    BALANCE_ID BIGSERIAL,
    CARD_ID    BIGSERIAL NOT NULL,
    BALANCE_VALUE NUMERIC(19,2) NOT NULL,
    BALANCE_KIND VARCHAR(255) NOT NULL,
    PRIMARY KEY (BALANCE_ID),
    CONSTRAINT FK_CARD_ID FOREIGN KEY (CARD_ID)
        REFERENCES CARD (CARD_ID)
        ON DELETE CASCADE
);
