spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: bankinguser
    password: bankinguser
  jpa:
    hibernate:
      ddl-auto: validate
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 10050