DROP TABLE IF EXISTS ACCOUNT CASCADE;
CREATE TABLE ACCOUNT
(
    ACCOUNT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

CREATE TABLE BALANCE
(
    BALANCE_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID    BIGINT,
    BALANCE_VALUE NUMERIC(19, 2) NOT NULL,
    BALANCE_KIND  VARCHAR(255)   NOT NULL,
    CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID)
        ON DELETE CASCADE
);
