CREATE TABLE IF NOT EXISTS ACCOUNT
(
    ACCOUNT_ID   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID      BIGINT       NOT NULL,
    ACCOUNT_TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BALANCE
(
    BALANCE_ID    BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID    BIGINT         NOT NULL,
    BALANCE_VALUE NUMERIC(19, 2) NOT NULL,
    BALANCE_KIND  VARCHAR(255)   NOT NULL,
    CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CREDIT
(
    CREDIT_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CREDIT_AMOUNT NUMERIC(19, 2) NOT NULL DEFAULT 0,
    ACCOUNT_ID    BIGINT         NOT NULL,
    CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DEBIT
(
    DEBIT_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEBIT_AMOUNT NUMERIC(19, 2) NOT NULL DEFAULT 0,
    ACCOUNT_ID   BIGINT         NOT NULL,
    CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID) ON DELETE CASCADE
);
